modLoader = "javafml"
loaderVersion = "${neo_loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/Khajiitos/ServerCountryFlags/issues"

[[mixins]]
config="servercountryflags.mixins.json"

[[mods]]
modId = "servercountryflags"
version = "${version}"
logoFile="icon.png"
displayName = "Server Country Flags"
authors = "Khajiitos"
displayURL="https://github.com/Khajiitos/ServerCountryFlags"
description = '''Shows the flag of where a server is located.'''
updateJSONURL = "https://updates.khajiitos.fun/server-country-flags/updates-neoforge.json"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.servercountryflags]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"